#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_hetero.py DIR  -- overwrite Cstar_solid.h5 in a solid_aniso case (already generated by
../mpi_compare/mkcase.py) with a HETEROGENEOUS isotropic solid: Vp varies linearly in x
across the physical domain [0,LX]. Vs, Rho constant. Used by item B (PML heterogeneous
inherit): the reader clamps sampling to the domain edge in the PML axis, so the left PML
(x<0) must freeze to Vp(x=0) and the right PML (x>LX) to Vp(x=LX).

Prints the expected edge C11 (=lambda+2mu) at x=0 and x=LX for the checker.
"""
import sys
import numpy as np
import h5py

LX = 500.0                     # must match mkcase domain
VP0, VP1 = 2000.0, 3200.0      # Vp at x=0 and x=LX (linear in between)
VS, RHO = 1150.0, 2200.0
NX = 21                        # sampling grid resolution in x (fine enough to see the gradient)


def cij_iso(vp, vs, rho):
    mu = rho * vs * vs
    lam = rho * (vp * vp - 2 * vs * vs)
    return {"C11": lam + 2 * mu, "C22": lam + 2 * mu, "C33": mu,
            "C12": lam, "C13": 0.0, "C23": 0.0, "Rho": rho}


def write(path):
    x = np.linspace(0.0, LX, NX)
    vp = VP0 + (VP1 - VP0) * x / LX               # linear Vp(x)
    # samples grid: dims (NX, 2) -> varies in x (index 0), constant in z (index 1)
    with h5py.File(path, "w") as f:
        for comp in ("C11", "C22", "C33", "C12", "C13", "C23", "Rho"):
            grid = np.zeros((NX, 2), dtype=np.float64)
            for i in range(NX):
                grid[i, :] = cij_iso(vp[i], VS, RHO)[comp]
            g = f.create_group(comp)
            g.create_dataset("samples", data=grid)
            g.attrs["xMinGlob"] = np.array([0.0, 0.0], dtype=np.float64)
            g.attrs["xMaxGlob"] = np.array([LX, 300.0], dtype=np.float64)
    # The PML is isotropic: it carries the iso projection (Lambda/Mu), NOT the full tensor.
    # For this iso-built field the projection recovers lambda = rho*(vp^2-2*vs^2). Print the
    # expected FROZEN lambda at each face (left=x0, right=xLX) for the checker.
    lam0 = RHO * (VP0 * VP0 - 2 * VS * VS)
    lam1 = RHO * (VP1 * VP1 - 2 * VS * VS)
    print("%.6e %.6e" % (lam0, lam1))   # expected frozen edge Lambda (left, right)


if __name__ == "__main__":
    write(sys.argv[1])
