#!/bin/bash

#PBS -S /bin/bash
#PBS -N TEST3D_1-run
#PBS -o output_run.txt
#PBS -j oe
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=12:mpiprocs=12
# #PBS -l select=1:ncpus=1:mpiprocs=1
#PBS -m e -M lucianopaludo123@gmail.com 
#PBS -q iceq
# #PBS -q icexq

# chargement des modules
module load intel-compiler/14.0.0
module load intel-mkl/11.1.0
module load intel-mpi/4.0.0.028
module load hdf5/1.8.12

# On se place dans le repertoire depuis lequel le job a ete soumis
cd $PBS_O_WORKDIR

cat $PBS_NODEFILE | uniq > mpd.hosts
nb_nodes=`cat mpd.hosts|wc -l`

mpirun --rsh=ssh -n $nb_nodes -f mpd.hosts -np 12 $HOME/workspace/SEM_RF2/build/SEM3D/sem3d.exe
# mpirun --rsh=ssh -n $nb_nodes -f mpd.hosts -np 1 $HOME/workspace/SEM_RF2/build/SEM3D/sem3d.exe
