# - Find FFTW3
# Find the FFTW3 (network Common Data Form) includes and library
#
# This module defines
#  FFTW3_FOUND
#  FFTW3_INCLUDE_DIR
#  FFTW3_LIBRARY
#  FFTW3_MPI_LIB
#  FFTW3_THREAD_LIB
#  FFTW3_CPP_LIBRARY
#  FFTW3_FORTRAN_LIBRARY
#

FIND_PATH(FFTW3_INCLUDE_DIR
  NAMES fftw3.h
  PATHS
  $ENV{FFTW3_ROOT}
  PATH_SUFFIXES include
)

FIND_LIBRARY(FFTW3_LIBRARY NAMES fftw3
  PATHS $ENV{FFTW3_ROOT}
  PATH_SUFFIXES lib/
  )

FIND_LIBRARY(FFTW3_MPI_LIB NAMES fftw3_mpi
  PATHS $ENV{FFTW3_ROOT}
  PATH_SUFFIXES lib/
  )
FIND_LIBRARY(FFTW3_THREAD_LIB NAMES fftw3_threads
  PATHS $ENV{FFTW3_ROOT}
  PATH_SUFFIXES lib/
)

IF(FFTW3_INCLUDE_DIR)
  SET(FFTW3_FOUND "YES")
  SET(FFTW3_LIBRARIES ${FFTW3_LIBRARY} ${FFTW3_MPI_LIB} ${FFTW3_THREADS_LIB})
ELSE(FFTW3_INCLUDE_DIR)
  SET(FFTW3_FOUND "NO")
ENDIF(FFTW3_INCLUDE_DIR)

IF(FFTW3_FOUND)
  IF(NOT FFTW3_FIND_QUIETLY)
    MESSAGE(STATUS "Found FFTW3: ${FFTW3_LIBRARY} ${FFTW3_INCLUDE_DIR}")
  ENDIF(NOT FFTW3_FIND_QUIETLY)
ELSE(FFTW3_FOUND)
  IF(FFTW3_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find FFTW3")
  ENDIF(FFTW3_FIND_REQUIRED)
ENDIF(FFTW3_FOUND)

MARK_AS_ADVANCED(
  #FFTW3_LIBRARY
  FFTW3_INCLUDE_DIR
)
